### ISSUE TITLE
how run this project?

### ISSUE THREAD

**Issue by aaa-engi** [arpit-jadon/FireNet-LightWeight-Network-for-Fire-Detection#3]
hi,
please explain how run this code of project on jupyter notebook?
some line of code has errors........

**Comment by aaa-engi** [comment]
I want to run this codes....
please help me....

**Comment by expoli** [comment]
Hi! guys, I forked this repo and i add some python code maybe it can help you.

The URL: https://github.com/expoli/FireNet-LightWeight-Network-for-Fire-Detection/tree/master/Codes/python

**Comment by arpit-jadon** [comment]
Hi! @aaa-engi , you can either use the pre-trained model for testing on different images directly or you can use the model for live fire detection with the help of real_time_detection script. You can also train the network on some other datasets using the training script, if you want. Also, if you want an embedded hardware implementation then you can deploy the vision algorithm to a Raspberry Pi and interface it with an Arduino micro-controller as mentioned in the paper.
